### ISSUE TITLE
Maybe a mistake?

### ISSUE THREAD

**Issue by beijiguang94** [tud-hri/irlmodelvalidation#1]
Thanks for your sharing. But maybe a mistake exists in the function **calculate_new_state** of **irlagent.py**:
`x_new = np.dot(np.array([[1, 0, dt, 0], [0, 1, 0, dt], [0, 0, 1, 0], [0, 0, 0, 1]]), x) + np.dot(np.array([[0, 0], [0, 0], [dt, 0], [0, dt]]), u)`
a correct one should be:
`x_new = np.dot(np.array([[1, 0, dt, 0], [0, 1, 0, dt], [0, 0, 1, 0], [0, 0, 0, 1]]), x) + np.dot(np.array([[0.5 * dt ** 2, 0], [0, 0.5 * dt ** 2], [dt, 0], [0, dt]]), u)`

**Comment by OlgerSiebinga** [comment]
Hi @beijiguang94! 

Thanks for spotting this, you are right! 
However, I think this was simplified because the induced error is very small. This is because the time steps are quite small (1/25 s) and the time that vehicles are simulated is also limited (usually around 300 frames = 12 s). Finally, it has no consequences for IRL learning because these simplified dynamics are used for both simulation and learning. 
Anyway, I'll double-check the induced error and see if it has any effects on the outcome of the IRL process.

**Comment by beijiguang94** [comment]
Thanks. I have another doubt: when learning the parameterized reward function it used x-velocity and y-velocity as the control input; yet when simulating with the learned reward function, it used x-acceleration and y-acceleration as the control input. I don't know for sure if it is logical even though the velocity data of the HighDDataset seems a little bit inaccurate and the acceleration seems even wired.

**Comment by OlgerSiebinga** [comment]
Yes, that was a difficult point indeed. In my opinion, the accelerations in the HighD dataset are not accurate enough to be used for the learning (I re-simulated the traces based on the accelerations alone, and the errors were substantial). On the other hand, I wanted to keep the model as close as possible to other IRL-based models. Therefore, I decided to use acceleration in the execution but velocity in the learning phase. 

I think this is not a big problem because the aim of the learning phase is to learn the reward function. It maximizes the likelihood that the current behavior is the result of a certain reward function. So the method of control input (acceleration vs direct control of velocities) should not matter for the learned reward function. Unfortunately, I could not verify this because of the inaccurate accelerations in the dataset.

**Comment by beijiguang94** [comment]
Yeah, I get your idea. However, in the learning stage, only the velocities data were used and the (x, y) was generated by the function **calculate_new_state**. Why not use the original (x, y) dataset instead to learn the reward function?
In addition, I found that the learned <img src="http://chart.googleapis.com/chart?cht=tx&chl= \theta" style="border:none;"> remained almost the same as its initial value, no matter what datasets and agents. I feel confused about the problem.

**Comment by OlgerSiebinga** [comment]
The learning phase uses the same pipeline as the model would use in the simulation. The reason is that the agent would make a decision based on this (potentially faulty) prediction, not on the actual outcome. So to determine the likelihood that the agent makes a decision based on a specific reward function combined with a prediction, the same prediction needs to be used. (the prediction, in this case, cannot be completely the same because one uses velocity and the other acceleration, but at least it is an approximation of the prediction.)

Regarding the values of θ that you found. I think this is yet another indication that the used model cannot accurately describe individual human drivers. Does this help take away your confusion?

**Comment by beijiguang94** [comment]
Yeah, I follow you. So the proposed model is a trial. And there may be some other methods to improve its representative performance, which is worth further investigation.
![0E5D5268](https://user-images.githubusercontent.com/29849449/167871982-e49d23f2-be81-4565-9749-9c21b77c6abd.png)
